# Generated by Django 5.0 on 2023-12-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("ingredients", models.TextField()),
                ("favorite", models.BooleanField(default=False)),
                (
                    "difficulty",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")],
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
            ],
        ),
    ]
