# Generated by Django 5.0 on 2023-12-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
